### PR TITLE
Update surfman

### PR DESCRIPTION
**Pull request by mukilan**
To complete the update of winit used by Servo (servo/servo#29382), a new version 0.6.0 of surfman has been published to crates.io (servo/surfman#249). In order to avoid mismatched types due to duplicated versions of surfman, we will need to update all references in Servo to the same version (0.6.0). 

I've bumped version of this crate but I see current version of this create 0.7.0 was never published to crates.io. Please let me know of this version bump is not needed.

### CODE REVIEW

**Comment by jdm** [comment]
We just got publishing rights this week. Might as well stick with 0.7.0.

**Review by jdm — APPROVED** [review]

**Comment by atouchet** [comment]
Can this be published to crates.io now?

**Comment by mukilan** [comment]
I can publish main branch as 0.7.0. @jdm can I go ahead?

**Comment by jdm** [comment]
Yep!

**Comment by mukilan** [comment]
surfman-chain 0.7.0 has been published.

**Pull request merged**
