### PR TITLE
Update surfman.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Review by philip-lamb — APPROVED** [review]

**Comment by jdm** [comment]
@asajeffrey looks like we never hooked up homu.

**Comment by asajeffrey** [comment]
We probably should move this over to the servo org and hook up homu.

**Comment by jdm** [comment]
Please publish when you can, too!

**Comment by jdm** [comment]
Publish ping!

**Comment by asajeffrey** [comment]
Done!

**Pull request merged**
