### PR TITLE
Support preserving the drawing buffer between swaps.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by asajeffrey** [comment]
LGTM. Can you add a major version bump and I'll merge and publish it?

**Comment by asajeffrey** [comment]
Hmm, we could avoid the major bump with a different API, which adds a function to blit the front buffer to the back buffer.

**Comment by jdm** [comment]
I looked into that at first, but it's possible for the front buffer to be taken by the consumer before it can be blitted. The blit needs to happen while we know the status of both surfaces.

**Comment by asajeffrey** [comment]
Good point.

**Pull request merged**
